---
name: Feature Request
description: Suggest an idea or improvement.
title: "[Feature]: "
labels: ["type: enhancement", "status: needs-triage"]
assignees: ["{VAR_USERNAME}"]
body:
    - type: textarea
      id: problem
      attributes:
          label: What problem does this solve?
          description: Describe the benefit this feature would provide to the project.
      validations:
          required: true
    - type: textarea
      id: solution
      attributes:
          label: Proposed solution
          description: Provide a clear and concise description of what specific change you would like.
      validations:
          required: true
    - type: textarea
      id: alternatives
      attributes:
          label: Alternatives you have considered
          description: Provide a description of any alternative solutions or features you've considered.
      validations:
          required: false
    - type: textarea
      id: context
      attributes:
          label: Additional context
          description: Screenshots, links, mockups.
      validations:
          required: false
    - type: checkboxes
      id: checks
      attributes:
          label: Verification
          options:
              - label: I have searched existing issues and found no duplicate.
                required: true
              - label: This is not implemented in the latest version.
                required: true
              - label: I've read and agree with the [Code of Conduct](https://github.com/{VAR_USERNAME}/{VAR_REPO}/blob/{VAR_MAIN_BRANCH}/docs/CODE_OF_CONDUCT.md)
                required: true
              - label: It doesn't overlap with existing items in the [Todo List](https://github.com/{VAR_USERNAME}/{VAR_REPO}/blob/{VAR_MAIN_BRANCH}/docs/TODO.md)
                required: true
