---
name: Mac Tests

on:
    push:
        branches: [stable, main, master]
    pull_request:
        branches: [stable, main, master]

jobs:
    build:
        name: Test Program on MacOS
        runs-on: macos-latest

        steps:
            - name: Check out code from GitHub
              uses: actions/checkout@v7

            - name: Set up Python
              uses: actions/setup-python@v7
              with:
                  python-version: "3.14"

            - name: Install dependencies
              run: |
                  python3 -m pip install --upgrade pip
                  pip3 install -r requirements.txt

            - name: Build Executable
              run: |
                  chmod +x ./build-scripts/build-mac.sh
                  ./build-scripts/build-mac.sh

            - name: Verify build outputs
              run: |
                  expected=(
                      "main.app/Contents/MacOS/webhook-manager"
                  )

                  for file in "${expected[@]}"; do
                      if [[ ! -f "$file" ]]; then
                          echo "::error::Build output missing: $file"
                          exit 1
                      else
                          echo "OK: $file"
                      fi
                  done

            - name: Compute Commit SHA
              id: vars
              run: |
                  echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

            - name: Archive artifact
              uses: actions/upload-artifact@v7
              with:
                  name: webhook-manager-mac_${{ steps.vars.outputs.sha_short }}
                  path: |
                      main.app/
